### ISSUE TITLE
Initial Curation of biolog data: adenosine

### ISSUE THREAD

**Issue by tiekneeshrimp** [pnnl-predictive-phenomics/csc009-gem#23]
Adenosine causing error after direct handling by @mcnaughtonadm :
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mcna892/Library/CloudStorage/OneDrive-PNNL/Desktop/Projects/csc009-gem/.venv/lib/python3.12/site-packages/cobra/core/dictlist.py", line 527, in __getattr__
    raise AttributeError(f"DictList has no attribute or entry {attr}")
AttributeError: DictList has no attribute or entry EX_adn_e```

Removing from **biolog_curtobacterium1.csv** file to determine if that will stop model from erroring, since there is no growth for that metabolite anyway.

**Comment by tiekneeshrimp** [comment]
removed:
EX_adn_e
EX_tym_e
EX_pyr_e
EX_ad_e, True, 10
EX_trp__L_e, False, 10
EX_glyclt_e, True, 10
EX_glu__D_e, True, 10
EX_erthrs_e, True, 10
EX_gua_e, True, 10
EX_gsn_e, True, 10
EX_rbl__B_e, True, 10

 need to add above!

**Comment by tiekneeshrimp** [comment]
solved with branch 19's updated update_model.py, needed to curate model
